### ISSUE TITLE
team_up App is not getting downloaded while cloning

### ISSUE THREAD

**Issue by Madhurireddy1** [ShivamBhirud/Team-up#18]
IDK why I've tried cloning and downloading zip as well but the team_up folder is not getting downloaded. 
<img width="1440" alt="Screenshot 2021-06-06 at 10 46 48 PM" src="https://user-images.githubusercontent.com/66663040/120933761-2db6da00-c719-11eb-8205-0ebd50c6b694.png">

**Comment by ShivamBhirud** [comment]
That is strange. Try forking the project again and then clone it. Firstly, remove everything from your GitHub and delete the folders from your local and then start fresh. Technically when we clone a project it should pull whatever we have in the remote repository.

**Comment by Madhurireddy1** [comment]
I think I figured it out, it's considering both Team_Up and team_up as the same since they have the same names and it's only downloading one. I downloaded the separate folder using 'https://minhaskamal.github.io/DownGit/#/home'. I'll just change the team_up name to something and try.

**Comment by ShivamBhirud** [comment]
Okay, sounds logical. Give it a try and thanks for pointing it out.
